### ISSUE TITLE
Debug/test code still in there. :) 

### ISSUE THREAD

**Issue by JoshMcCullough** [speendo/OpenSCAD-Round-Primitives#1]
Thanks for this! Just FYI the end of each scad file has some test code still in place.

**Comment by speendo** [comment]
Good to know somebody except me uses this library :+1: 

I would like to add some more features before finally releasing it. Let me know, if you want to join me!

The test code is there on purpuse. When you iport the library with `use <filename>` (see [here](https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/Include_Statement)), the test code shouldn't be a problem. Or is it?

**Comment by JoshMcCullough** [comment]
When you include the library, the test models are rendered.

**Comment by speendo** [comment]
yes, that's on purpose.

It's better to use command `use <filename>` instead of `include <filename>`

**Comment by JoshMcCullough** [comment]
Ah, thanks.

**Comment by JoshMcCullough** [comment]
BTW here's what I'm using your library for: https://github.com/JoshMcCullough/bbBrix (includes attribution link).

**Comment by speendo** [comment]
That's awesome! Great idea! That's what I love about OpenSCAD.

Let me know if my library misses a feature you need.

**Comment by JoshMcCullough** [comment]
Will do, but so far so good.
